// Route data generated by scripts/route_elevation.mjs into src/content/routes/{slug}.json
import type { RouteData } from '../components/RouteMap.astro';
const files = import.meta.glob<{ default: RouteData }>('/src/content/routes/*.json');
export async function getRouteData(slug: string, dataFile?: string): Promise<RouteData | null> {
  const key = dataFile ? '/src/' + dataFile.replace(/^\/?(src\/)?/, '') : `/src/content/routes/${slug}.json`;
  const load = files[key];
  if (!load) return null;
  const d = (await load()).default;
  return d && d.points?.length > 1 ? d : null;
}
